# tasks file for jenkins
---
- name: wait for server to come online
  command: "curl -s -o /dev/null -I -w '%{http_code}' {{ jenkins_url }}/cli/"
  register: jenkins_online
  until: "jenkins_online.stdout == '200'"
  retries: 10
  delay: 10
  changed_when: false
  tags: [configuration, jenkins, jenkins-online]

- name: create (client) directory
  file:
    path: "{{ jenkins_cli_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, jenkins, jenkins-cli-directory]

- name: download (latest) client
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cli_path }}"
    owner: root
    group: root
    mode: 0644
  register: jenkins_cli_download
  until: "'OK' in jenkins_cli_download.msg or 'file already exists' in jenkins_cli_download.msg"
  retries: 10
  delay: 10
  tags: [configuration, jenkins, jenkins-cli-download]
