# tasks file for jenkins
---
- name: configure | update configuration file
  template:
    src: etc/default/jenkins.j2
    dest: /etc/default/jenkins
    owner: root
    group: root
    mode: 0644
  notify: restart jenkins
  tags:
    - jenkins-configure-etc-default

- name: configure | email (tasks mailer)
  template:
    src: var/lib/jenkins/hudson.tasks.Mailer.xml.j2
    dest: "{{ jenkins_home }}/hudson.tasks.Mailer.xml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0644
  notify: restart jenkins
  when: jenkins_tasks_mailer_manage
  tags:
    - jenkins-configure-tasks-mailer

- name: configure | start and enable service
  service:
    name: jenkins
    state: started
    enabled: true
  tags:
    - jenkins-configure-start-enable-service]
