# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ jenkins_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ jenkins_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-additional

- name: provide java
  when: not jenkins_assume_java_provided | bool
  tags:
    - jenkins-install-dependencies
    - jenkins-install-dependencies-java
  block:
    # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    - name: ensure man directory
      ansible.builtin.file:
        path: /usr/share/man/man1
        state: directory
        recurse: true
      when:
        - ansible_distribution_major_version is version('18', '>=')

    - name: install | dependencies (java)
      ansible.builtin.apt:
        name: "{{ jenkins_java_dependencies }}"
        state: "{{ apt_install_state | default('latest') }}"

- name: install | jenkins
  ansible.builtin.apt:
    name: jenkins
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-jenkins
