# tasks file for jenkins
- name: install | dependencies
  apt:
    name: "{{ jenkins_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-dependencies

- name: install | additional
  apt:
    name: "{{ jenkins_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-additional

- name: install | dependencies (java)
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ jenkins_java_dependencies }}"
  when: not jenkins_assume_java_provided
  tags:
    - jenkins-install-dependencies
    - jenkins-install-dependencies-java

- name: install | jenkins
  apt:
    name: jenkins
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-jenkins
