# tasks file for jenkins
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_dependencies
  tags: [configuration, jenkins, jenkins-dependencies]

- name: install additional
  apt:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_install
  tags: [configuration, jenkins, jenkins-additional]

- name: install dependencies (java)
  apt:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_java_dependencies
  when: jenkins_assume_java_provided == false and jenkins_java_dependencies
  tags: [configuration, jenkins, jenkins-dependencies-java]

- name: install
  apt:
    name: jenkins
    state: latest
  register: jenkins_installation_status
  tags: [configuration, jenkins, jenkins-install]

- name: wait for initial admin password file
  wait_for:
    path: "{{ jenkins_initial_admin_password_file }}"
    state: present
  tags: [configuration, jenkins, jenkins-install, jenkins-get-initial-admin-password]

- name: get initial admin password
  command: cat {{ jenkins_initial_admin_password_file }}
  register: get_initial_admin_password
  changed_when: false
  tags: [configuration, jenkins, jenkins-install, jenkins-get-initial-admin-password]
