# tasks file for jenkins
---
- name: create (plugins) directory
  file:
    path: "{{ jenkins_plugins_path }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0755
  tags: [configuration, jenkins, jenkins-plugins-directory]

- name: list installed plugins
  shell: "java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }} list-plugins | awk '{ print $1 }'"
  when: jenkins_plugins
  register: jenkins_plugins_installed
  changed_when: False
  tags: [configuration, jenkins, jenkins-plugins-installed]

- name: install (new) plugins
  command: "java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }} install-plugin {{ item }}"
  when: jenkins_plugins and item not in jenkins_plugins_installed.stdout_lines
  with_items: jenkins_plugins
  notify: restart jenkins
  tags: [configuration, jenkins, jenkins-plugins-install]

- name: list updatable plugins
  shell: "java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }} list-plugins | grep -e ')$' | awk '{ print $1 }'"
  register: jenkins_plugins_updatable
  changed_when: False
  tags: [configuration, jenkins, jenkins-plugins-updatable]

- name: update (existing) plugins
  command: "java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }} install-plugin {{ item }}"
  when: jenkins_plugins_updatable.stdout_lines
  with_items: jenkins_plugins_updatable.stdout_lines
  notify: restart jenkins
  tags: [configuration, jenkins, jenkins-plugins-update]
