# tasks file for jenkins
---
- name: repository | public key
  apt_key:
    id: D50582E6
    url: https://jenkins-ci.org/debian/jenkins-ci.org.key
    state: present
  tags:
    - jenkins-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ jenkins_repositories }}"
  tags:
    - jenkins-repository-add
