# tasks file for jenkins
---
- name: add public key
  apt_key:
    id: D50582E6
    url: https://jenkins-ci.org/debian/jenkins-ci.org.key
    state: present
  tags: [configuration, jenkins, jenkins-public-key]

- name: add jenkins repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: yes
  with_items: jenkins_repositories
  tags: [configuration, jenkins, jenkins-repository]
