# tasks file
---
- name: repository | add public key
  apt_key:
    id: FCEF32E745F2C3D5
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  tags:
    - jenkins-repository-public-key

- name: repository | add repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ jenkins_repositories }}"
  tags:
    - jenkins-repository-repository

- name: repository | add ppa (java)
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    update_cache: true
    mode: 0644
  when:
    - not jenkins_assume_java_provided
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('14.04', '<=')
  tags:
    - jenkins-repository-repository-java
