# tasks file for jenkins
---
- name: repository | add public key
  apt_key:
    id: 9B7D32F2D50582E6
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  tags:
    - jenkins-repository-public-key

- name: repository | add repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ jenkins_repositories }}"
  tags:
    - jenkins-repository-repository

- name: repository | add ppa (java)
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    update_cache: true
  when: >
    (jenkins_assume_java_provided == false)
    and (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('14.04', '<='))
  tags:
    - jenkins-repository-repository-java
