# handlers file for jenkins
---
- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: safe-restart jenkins
  command: "java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }} safe-restart"
