# handlers file for jenkins
---
- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: logout jenkins cli
  shell: >
    java -jar {{ jenkins_cli_jar }}
    -s '{{ jenkins_url }}'
    --username={{ jenkins_admin_username }} --password={{ jenkins_admin_password }}
    logout
  ignore_errors: true

- name: logout jenkins cli with password file
  shell: >
    java -jar {{ jenkins_cli_jar }}
    -s '{{ jenkins_url }}'
    --username={{ jenkins_admin_username }} --password-file={{ jenkins_admin_password_file }}
    logout
  ignore_errors: true
